# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef043648a076864a2184d8542a01a762dc7e8715bfdae8d9e5eca5b1f99a3e66f1a717f5745d82d473333925f36df5e954148d78e756a4cb5b1abe4cc3931232

test:
  secret_key_base: 0b4f3c19e9228db5fbceeb7b1024db1156a2b997de6a35f8db05e119a9ba1689b14c60778a37aee058d2008296304c053f786989933317ba499585ba2a2c690a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
